name: Create Automatic Release

on:
  push:
    branches:
      - master  

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Get version
        id: get_version
        run: |
          # Use the commit SHA for the release version
          echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          # Get the current date for the release name
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Create ZIP archive
        run: |
          # Exclude .git directory and GitHub workflows when creating the zip
          zip -r OmniBar.zip . -x "*.git*" "*.github*"
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ env.DATE }}-${{ env.VERSION }}
          name: Release ${{ env.DATE }} (${{ env.VERSION }})
          draft: false
          prerelease: false
          files: |
            OmniBar.zip
          body: |
            Replace base OmniBar folder with this one. Updating via curseforge will overwrite this version back to base OmniBar.

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 3  
          delete_tags: true  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}