name: Create Automatic Release

on:
  push:
    branches:
      - master  

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Get version
        id: get_version
        run: |
          # Use the commit SHA for the release version
          echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          # Get the current date for the release name
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Create ZIP archive
        run: |
          # Exclude .git directory and GitHub workflows when creating the zip
          zip -r release.zip . -x "*.git*" "*.github*"
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ env.DATE }}-${{ env.VERSION }}
          name: Release ${{ env.DATE }} (${{ env.VERSION }})
          draft: false
          prerelease: false
          files: |
            release.zip
          body: |
            Automatic release created from commit ${{ env.VERSION }} on ${{ env.DATE }}
            
            This release was automatically generated by GitHub Actions.